### ISSUE TITLE
Add Link Preview and Social Media Sharing meta tags. 

### ISSUE THREAD

**Issue by vaibhavAP** [WorldEnterpriseGroup/taomgt#11]
There is no link preview and social media sharable links. No preview will be visible on Facebook and Twitter as there are no meta tags related to them. Add meta tags such that when we share our website link with anyone they can at least see the preview.

Article on how meta tags impact SEO:
https://www.wordstream.com/meta-tags

Essential meta tags on social media:
https://css-tricks.com/essential-meta-tags-social-media/

- [ ] Add meta tags that help to create preview on sites like WhatsApp and messenger.

- [ ] Add meta tags which create twitter preview

- [ ] Add meta tags for Facebook preview ( read about the OG tags)

- [ ] Preview should contain an image.

- [ ] It should have a title.
